#See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER app
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["src/FrogPay.CRUD.API/FrogPay.CRUD.API.csproj", "src/FrogPay.CRUD.API/"]
COPY ["src/FrogPay.CRUD.Domain/FrogPay.CRUD.Domain.csproj", "src/FrogPay.CRUD.Domain/"]
COPY ["src/FrogPay.CRUD.Infrastructure/FrogPay.CRUD.Infrastructure.csproj", "src/FrogPay.CRUD.Infrastructure/"]
RUN dotnet restore "./src/FrogPay.CRUD.API/FrogPay.CRUD.API.csproj"
COPY . .
WORKDIR "/src/src/FrogPay.CRUD.API"
RUN dotnet build "./FrogPay.CRUD.API.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./FrogPay.CRUD.API.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "FrogPay.CRUD.API.dll"]